-- 081_despacho_numero_from_cotizacion.sql
-- Fix: asegurar que notas_despacho.numero siempre coincida con cotizaciones.numero
--
-- Problema: La columna es GENERATED ALWAYS AS IDENTITY, lo cual impide que un trigger
-- o un INSERT normal setee el valor. Solo funciona con OVERRIDING SYSTEM VALUE.
-- El worker usa REST API (PostgREST) que no soporta OVERRIDING SYSTEM VALUE.
--
-- Solución: Cambiar a GENERATED BY DEFAULT para permitir valor explícito en INSERT,
-- y agregar un trigger que copie el numero de la cotización cuando no se pasa uno.

-- 1. Cambiar la columna de GENERATED ALWAYS a GENERATED BY DEFAULT
ALTER TABLE public.notas_despacho
  ALTER COLUMN numero SET GENERATED BY DEFAULT;

-- 2. Trigger que copia el numero de la cotización al despacho
CREATE OR REPLACE FUNCTION public.trg_despacho_copiar_numero()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  v_numero INTEGER;
BEGIN
  -- Si viene cotizacion_id, copiar su numero
  IF NEW.cotizacion_id IS NOT NULL THEN
    SELECT numero INTO v_numero
    FROM public.cotizaciones
    WHERE id = NEW.cotizacion_id;

    IF v_numero IS NOT NULL THEN
      NEW.numero := v_numero;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_despacho_copiar_numero ON public.notas_despacho;
CREATE TRIGGER trg_despacho_copiar_numero
  BEFORE INSERT ON public.notas_despacho
  FOR EACH ROW
  EXECUTE FUNCTION public.trg_despacho_copiar_numero();
