-- 127_fix_config_negocio_multitenant.sql
-- Libera la tabla configuracion_negocio de las restricciones de singleton (id=1)
-- para permitir múltiples configuraciones en el entorno multi-tenant.

DO $$
BEGIN
    -- 1. Eliminar la restricción CHECK que obliga a id=1
    ALTER TABLE public.configuracion_negocio DROP CONSTRAINT IF EXISTS configuracion_negocio_id_check;

    -- 2. Eliminar el valor por defecto fijo (1)
    ALTER TABLE public.configuracion_negocio ALTER COLUMN id DROP DEFAULT;

    -- 3. Convertir id en una columna IDENTITY (autoincremental)
    -- Primero verificamos si ya es identity para evitar errores
    IF NOT EXISTS (
        SELECT 1 FROM pg_attribute 
        WHERE attrelid = 'public.configuracion_negocio'::regclass 
        AND attname = 'id' 
        AND attidentity <> ''
    ) THEN
        ALTER TABLE public.configuracion_negocio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2);
    END IF;

    -- 4. Asegurar que cuenta_id sea único (PK lógica para multi-tenant)
    -- La migración 113 ya debería haberlo hecho, pero lo reforzamos aquí
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'configuracion_negocio_cuenta_id_key') THEN
        ALTER TABLE public.configuracion_negocio ADD CONSTRAINT configuracion_negocio_cuenta_id_key UNIQUE (cuenta_id);
    END IF;

END $$;

COMMENT ON TABLE public.configuracion_negocio IS 'Configuración de negocio por cuenta (Multi-tenant).';
